global.DATABASE = 'bytespeedtestdb'
global.USERNAME = 'bytespeedtestdb'
global.PASSWORD = 'bytespeed'
global.HOSTNAME = 'db4free.net'
global.PRIVATE_KEY = 'ACQwJ2QOpMt2aIgxI3q8XNrjdtzG/eXFPDwgpEY2L5k'